name: Fetch NSE Cookies and Store via API

on:
  schedule:
    - cron: '45 3 * * *'                # 9:15 AM IST
    - cron: '0,15,30,45 4-18 * * *'     # 9:30 AM to 11:45 PM IST
  workflow_dispatch:                   # Manual trigger from GitHub UI

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run NSE cookie fetch script
        run: python nse-cookies/dev-fetch-nsit-and-nseappid.py
