name: Run Python script

on:
  schedule:
    - cron: '30 19,2,4,6,8,11,13,16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas lxml html5lib
    - name: Run script
      run: python fii/fpi-sectore-invest-nsdl-trial.py
